param(
  [string]$Workspace = "",
  [string]$MvpDir = ""
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Workspace)) {
  $Workspace = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
}
if ([string]::IsNullOrWhiteSpace($MvpDir)) {
  $MvpDir = Join-Path $Workspace "product_data"
} elseif (-not [System.IO.Path]::IsPathRooted($MvpDir)) {
  $MvpDir = Join-Path $Workspace $MvpDir
}
$MvpDir = (Resolve-Path -LiteralPath $MvpDir).Path

function Get-SafeValue {
  param([object]$Row, [string]$Name, [string]$Default = "")
  if ($null -eq $Row -or -not ($Row.PSObject.Properties.Name -contains $Name)) { return $Default }
  $value = [string]$Row.$Name
  if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
  return $value.Trim()
}

function New-Slug {
  param([string]$Text)
  $slug = ($Text.ToLowerInvariant() -replace '[^a-z0-9]+', '-').Trim('-')
  if ([string]::IsNullOrWhiteSpace($slug)) { return "lead" }
  return $slug
}

$crmPath = Join-Path $MvpDir "crm_import.csv"
$approvalPath = Join-Path $MvpDir "outreach_approval_queue.csv"
if (-not (Test-Path -LiteralPath $crmPath -PathType Leaf)) {
  throw "CRM import missing: $crmPath"
}
if (-not (Test-Path -LiteralPath $approvalPath -PathType Leaf)) {
  throw "Approval queue missing: $approvalPath"
}

$crmRows = @(Import-Csv -LiteralPath $crmPath -Encoding UTF8)
$approvalRows = @(Import-Csv -LiteralPath $approvalPath -Encoding UTF8)
$crmByCompany = @{}
foreach ($row in $crmRows) {
  $companyKey = (Get-SafeValue $row "company").ToLowerInvariant()
  if ($companyKey -and -not $crmByCompany.ContainsKey($companyKey)) {
    $crmByCompany[$companyKey] = $row
  }
}

$messages = New-Object System.Collections.Generic.List[object]
$index = 0
foreach ($approval in $approvalRows) {
  $index += 1
  $company = Get-SafeValue $approval "company" "unknown company"
  $companyKey = $company.ToLowerInvariant()
  $crm = if ($crmByCompany.ContainsKey($companyKey)) { $crmByCompany[$companyKey] } else { $null }
  $destinationType = Get-SafeValue $approval "destination_type" "unknown"
  $draftField = if ($destinationType -match 'whatsapp') { "whatsapp_opener" } else { "email_draft" }
  $body = if ($crm) { Get-SafeValue $crm $draftField } else { "" }
  if ([string]::IsNullOrWhiteSpace($body)) {
    throw "Approved, product-owner-supplied draft missing for $company ($draftField). This repository does not generate product claims."
  }

  $messages.Add([pscustomobject]@{
    message_id = ("msg-{0:D3}-{1}" -f $index, (New-Slug $company))
    company = $company
    channel = Get-SafeValue $approval "channel" "manual"
    destination = Get-SafeValue $approval "destination"
    destination_type = $destinationType
    subject = if ($crm) { Get-SafeValue $crm "email_subject" "Approved product information" } else { "Approved product information" }
    body = $body
    approval_status = Get-SafeValue $approval "approval_status" "DO_NOT_SEND_YET"
    source_url = Get-SafeValue $approval "source_url"
    owner = if ($crm) { Get-SafeValue $crm "owner" "" } else { "" }
    generated_at = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    send_status = "NOT_APPROVED"
    sent_at = ""
    notes = Get-SafeValue $approval "notes"
  }) | Out-Null
}

$messagePath = Join-Path $MvpDir "outbound_messages.csv"
$messages | Export-Csv -LiteralPath $messagePath -NoTypeInformation -Encoding UTF8

Write-Host "[OK] Product-owner drafts copied to: $messagePath"
Write-Host "[OK] Messages: $($messages.Count)"
Write-Host "[SAFE] No product descriptions or claims were generated by this script."
