import type { InstallerConfig } from "./contracts.js";

export const defaultInstallerConfig: InstallerConfig = {
  business: {
    legalName: "",
    brandName: "",
    website: "https://",
    country: "China",
    city: "",
    postalAddress: "",
    contactName: "",
    contactTitle: "Sales Manager",
    contactEmail: "",
    whatsapp: "",
    introduction: "",
  },
  product: {
    name: "",
    hsCode: "",
    specifications: [],
    sellingPoints: [],
    targetMarkets: [],
    buyerTypes: [],
    moq: "",
    leadTime: "",
    priceRule: "Quote according to specifications and application.",
  },
  ai: {
    baseUrl: "https://api.openai.com/v1",
    model: "",
  },
  feishu: {
    enabled: true,
    domain: "feishu",
    appId: "",
    setupConfirmed: false,
    crmName: "外贸获客CRM-生产版",
  },
  email: {
    mode: "gmail_pilot",
    fromAddress: "",
    fromName: "",
    replyTo: "",
    smtpHost: "smtp.gmail.com",
    smtpPort: 587,
    smtpUser: "",
    imapHost: "imap.gmail.com",
    imapPort: 993,
    imapUser: "",
    dailyLimit: 50,
    hourlyLimit: 20,
    unsubscribeText: "",
    domainAuthVerified: false,
    warmupComplete: false,
  },
  search: {
    provider: "searxng",
    baseUrl: "http://127.0.0.1:8888",
  },
  server: {
    host: "",
    port: 22,
    user: "root",
    authMode: "password",
    privateKeyPath: "",
    appDir: "~/export-ai-agent",
    replaceExistingEnv: false,
    hostFingerprint: "",
  },
  whatsapp: {
    enabled: false,
    setupConfirmed: false,
    graphApiVersion: "v23.0",
    phoneNumberId: "",
    templateName: "",
    templateLanguage: "en_US",
    publicBaseUrl: "",
    dailyLimit: 20,
  },
  confirmations: {
    publicDataOnly: true,
    humanApprovalBeforeSend: true,
    initialOutboundPause: true,
  },
};
